name: tillhub_sdk_flutter
description: The Tillhub SDK for Flutter
version: 0.1.0
homepage: https://github.com/tillhub/tillhub_sdk_flutter

environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  logging: ^0.11.3+2
  dio: ^3.0.8
  dio_retry: ^0.1.9-beta
  device_id: ^0.2.0
  connectivity: ^0.4.2
  jaguar_jwt: ^2.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter